server:
  port: 8081
spring:
  application:
    name: demo-provider
  datasource:
    url: jdbc:mysql://localhost:3306/heima111
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.itheima.pojo
  global-config:
    db-config:
      insert-strategy: not_empty # 只新增非空字段
      update-strategy: not_empty # 只更新非空字段
      id-type: auto # id自增长
logging:
  level:
    cn.itcast: debug